owner: garage44
repo: pyrite-uptime
sites:
  - name: Pyrite
    url: https://pyrite.video
  - name: Pyrite Beta
    url: https://beta.pyrite.video
  - name: Pyrite Deployment
    url: https://pyrite.video/deployment/upload
assignees:
  - jvanveen  
status-website:
  cname: uptime.pyrite.video
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/garage44/pyrite/main/public/logo.png
  name: Pyrite Uptime
  introTitle: "Pyrite uptime monitor"
  introMessage: Experiencing service failure? Just file an issue here and the royal we will take a look at it.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
